### ISSUE TITLE
Old keybinds don't work.

### ISSUE THREAD

**Issue by NopeNop3Nop3** [fortellgames/bw_bugtracker#27] opened 2024-05-17 16:29 UTC
In the new Alpha, keybinds such as Ctrl + Z for undoing actions no longer work.

**Comment by Aktion** [comment] 2024-05-17 16:48
I need a full list if you can

**Comment by ronald112** [comment] 2024-05-23 20:19
@NopeNop3Nop3 Ctrl + Z, Ctrl + Y should be fixed now

**Closed as completed** 2024-05-28 12:58 UTC
Labels: new bug 2024

**Comment by NopeNop3Nop3** [comment] 2024-06-08 16:04
Issue has returned as of 2.0.0.101

**Comment by ronald112** [comment] 2024-06-10 11:06
@NopeNop3Nop3 cannot reproduce it in 2.0.0.102. 

https://github.com/fortellgames/bw_bugtracker/assets/43217006/b9caf26b-342b-4eb2-83d3-475fbf16fc01
